### ISSUE TITLE
TypeError: Retry.__init__() got an unexpected keyword argument 'allowed_methods'

### ISSUE THREAD

**Issue by DimitrovC** [iamkubi/pydactyl#80]
**Describe the bug**
Pydactyl / Requests don't work on ubuntu 22.04 using python 3.11

**To Reproduce**
Code: client = PterodactylClient(API_Link, API_Code)

Error: 
Traceback (most recent call last):
  File "/var/www/discordbot/app.py", line 37, in <module>
    client = PterodactylClient(API_Link, API_Code)

  File "/usr/local/lib/python3.11/dist-packages/pydactyl/api_client.py", line 69, in __init__
    adapter = http_adapter(backoff_factor=backoff_factor,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pydactyl/api_client.py", line 16, in http_adapter
    retries = requests.adapters.Retry(
              ^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Retry.__init__() got an unexpected keyword argument 'allowed_methods'

**Expected behavior**
When i tried to run the code on my linux vps i expected to work perfectly because it worked on my windows pc normally.

**Environment**
 - pydactyl version - 2.0.4
 - Python version - 3.11

**Comment by iamkubi** [comment]
You need to update your requests library.  The version in dev-requirements.txt should work, although I suppose I should add a requirements.txt that includes the correct requests version.

**Comment by DimitrovC** [comment]
> You need to update your requests library. The version in dev-requirements.txt should work, although I suppose I should add a requirements.txt that includes the correct requests version.

Actually i have updated the requests library to the latest version and still getting this error

**Comment by iamkubi** [comment]
Technically it's the urllib3 version that requests depends on.  The `method_whitelist` parameter was was deprecated and removed from urllib3 1.26.0 onwards, as stated in the [release changelog](https://github.com/urllib3/urllib3/blob/master/CHANGES.rst#1260-2020-11-10).

If you install the "latest" requests version it will install a version of urllib3 that uses `allowed_methods` instead of `method_whitelist`.

**Comment by DimitrovC** [comment]
> Technically it's the urllib3 version that requests depends on. The `method_whitelist` parameter was was deprecated and removed from urllib3 1.26.0 onwards, as stated in the [release changelog](https://github.com/urllib3/urllib3/blob/master/CHANGES.rst#1260-2020-11-10).
> 
> If you install the "latest" requests version it will install a version of urllib3 that uses `allowed_methods` instead of `method_whitelist`.

Its working, thanks.
